"""empty message

Revision ID: e3a4c83143fd
Revises: 
Create Date: 2021-02-20 16:16:44.418914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a4c83143fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastUpdated', sa.DateTime(), nullable=False),
    sa.Column('sellPrice', sa.Float(precision=4), nullable=False),
    sa.Column('sellPrices', sa.PickleType(), nullable=True),
    sa.Column('sellVolume', sa.Integer(), nullable=False),
    sa.Column('sellMovingWeek', sa.Integer(), nullable=False),
    sa.Column('sellOrderAmount', sa.Integer(), nullable=False),
    sa.Column('sellOrders', sa.PickleType(), nullable=False),
    sa.Column('sellHistoricOrders', sa.PickleType(), nullable=False),
    sa.Column('buyPrice', sa.Float(precision=4), nullable=False),
    sa.Column('buyPrices', sa.PickleType(), nullable=True),
    sa.Column('buyVolume', sa.Integer(), nullable=False),
    sa.Column('buyMovingWeek', sa.Integer(), nullable=False),
    sa.Column('buyOrderAmount', sa.Integer(), nullable=False),
    sa.Column('buyOrders', sa.PickleType(), nullable=False),
    sa.Column('buyHistoricOrders', sa.PickleType(), nullable=False),
    sa.Column('margin', sa.Float(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('candle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priceType', sa.String(), nullable=False),
    sa.Column('timeframe', sa.Integer(), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(precision=4), nullable=False),
    sa.Column('high', sa.Float(precision=4), nullable=False),
    sa.Column('low', sa.Float(precision=4), nullable=False),
    sa.Column('close', sa.Float(precision=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specific_values', sa.PickleType(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candles',
    sa.Column('containee_id', sa.Integer(), nullable=True),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['containee_id'], ['candle.id'], ),
    sa.ForeignKeyConstraint(['container_id'], ['candle.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candles')
    op.drop_table('user_asset')
    op.drop_table('candle')
    op.drop_table('user')
    op.drop_table('asset')
    # ### end Alembic commands ###
